### ISSUE TITLE
Example files for input

### ISSUE THREAD

**Issue by emilhaegglund** [aswarren/pangenome_graphs#1]
I'm very interested in the script and tried to run it today, but I couldn't figure out what the format of the input-files should have. Can you please add an example input-file to the repository with the correct format? I tried to pass both .gff and .gbk files, resulting in that the script printed a warning that the line couldn't be parsed for every line of the files.

**Comment by aswarren** [comment]
Hi there, thanks for the interest. I have updated the repository with some initial information in the README concerning running and some example data from the paper. Support for GFF and GBK files is forthcoming *but* any provided file would need to communicate "protein family" information.
