### ISSUE TITLE
cannot run python fam_to_graph.py --layout --output data/BrucellaInversion/test_psgraph.gexf --patric_pgfam ./data/BrucellaInversion/*.tab

### ISSUE THREAD

**Issue by yseif** [aswarren/pangenome_graphs#6]
I've been trying to re-run the example command line:
python fam_to_graph.py --layout --output data/BrucellaInversion/test_psgraph.gexf --patric_pgfam ./data/BrucellaInversion/*.tab

I'm getting this warning: warning: couldn't parse line: 568815.3
Here's the output:
rf-graph: 15 nodes unexapanded
rf-graph:
nodes 4417
edges 9726
pg-graph:
nodes 3866
edges 4296
alt-nodes 162
laying out graph
--- 1.77395200729 seconds ---

And finally when I try loading the gexf file in python, I get the following:
File "<string>", line unknown
ParseError: no element found: line 1, column 0

Mainly because the gexf file is empty.

Should the input data be formatted differently from the example data in your data folder?

**Comment by jimnoneill** [comment]
@yseif I am running into the same exact issue. Did you solve this problem? Thanks!
